"""Add codes fields to BD_VENTAS

Revision ID: 6156d4d1c887
Revises: 
Create Date: 2025-05-03 20:48:23.648265

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6156d4d1c887'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BD_DEVOLUCIONES',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consecutivo', sa.String(length=20), nullable=False),
    sa.Column('codigo_vendedor', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('productos', sa.Text(), nullable=False),
    sa.Column('usos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['codigo_vendedor'], ['vendedores.codigo_vendedor'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consecutivo')
    )
    op.create_table('BD_EXTRAS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consecutivo', sa.String(length=20), nullable=False),
    sa.Column('codigo_vendedor', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('productos', sa.Text(), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['codigo_vendedor'], ['vendedores.codigo_vendedor'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consecutivo')
    )
    op.create_table('BD_VENTAS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consecutivo', sa.String(length=20), nullable=False),
    sa.Column('codigo_vendedor', sa.String(length=20), nullable=False),
    sa.Column('codigo_dev_anterior', sa.String(length=20), nullable=True),
    sa.Column('codigo_pedido', sa.String(length=20), nullable=True),
    sa.Column('codigo_extra', sa.String(length=20), nullable=True),
    sa.Column('codigo_dev_dia', sa.String(length=20), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('devolucion_anterior', sa.Integer(), nullable=False),
    sa.Column('pedido', sa.Integer(), nullable=False),
    sa.Column('extras', sa.Integer(), nullable=False),
    sa.Column('devolucion_dia', sa.Integer(), nullable=False),
    sa.Column('total_venta', sa.Float(), nullable=False),
    sa.Column('comision', sa.Float(), nullable=False),
    sa.Column('pagar_pan', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['codigo_vendedor'], ['vendedores.codigo_vendedor'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consecutivo')
    )
    with op.batch_alter_table('bd_devoluciones', schema=None) as batch_op:
        batch_op.drop_index('consecutivo')

    op.drop_table('bd_devoluciones')
    with op.batch_alter_table('bd_extras', schema=None) as batch_op:
        batch_op.drop_index('consecutivo')

    op.drop_table('bd_extras')
    with op.batch_alter_table('bd_ventas', schema=None) as batch_op:
        batch_op.drop_index('consecutivo')

    op.drop_table('bd_ventas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bd_ventas',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('consecutivo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('codigo_vendedor', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('fecha', sa.DATE(), nullable=False),
    sa.Column('devolucion_anterior', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('pedido', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('extras', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('devolucion_dia', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('total_venta', mysql.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('comision', mysql.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('pagar_pan', mysql.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['codigo_vendedor'], ['vendedores.codigo_vendedor'], name='bd_ventas_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('bd_ventas', schema=None) as batch_op:
        batch_op.create_index('consecutivo', ['consecutivo'], unique=True)

    op.create_table('bd_extras',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('consecutivo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('codigo_vendedor', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('fecha', sa.DATE(), nullable=False),
    sa.Column('comentarios', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('productos', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('usado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['codigo_vendedor'], ['vendedores.codigo_vendedor'], name='bd_extras_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('bd_extras', schema=None) as batch_op:
        batch_op.create_index('consecutivo', ['consecutivo'], unique=True)

    op.create_table('bd_devoluciones',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('consecutivo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('codigo_vendedor', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('fecha', sa.DATE(), nullable=False),
    sa.Column('comentarios', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('productos', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('usos', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['codigo_vendedor'], ['vendedores.codigo_vendedor'], name='bd_devoluciones_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('bd_devoluciones', schema=None) as batch_op:
        batch_op.create_index('consecutivo', ['consecutivo'], unique=True)

    op.drop_table('BD_VENTAS')
    op.drop_table('BD_EXTRAS')
    op.drop_table('BD_DEVOLUCIONES')
    # ### end Alembic commands ###
